#ifndef __WIVW_ERROR_H__
#define __WIVW_ERROR_H__
#include "errcode_module.h"

enum
{
	/* Generic Error defines */
	WIVW_SUCCESS							= SUCCESS,
	/* Common errors */
	WIVW_ERROR_GENERAL						= ERROR_W_IVW + 1,
	WIVW_ERROR_NOT_INIT,
	WIVW_ERROR_ALREADY_START,
	WIVW_ERROR_NOT_START,
	WIVW_ERROR_RESOURCE_NOT_EXIST,
	WIVW_ERROR_INVALID_PARA,
	WIVW_ERROR_INVALID_PARA_VALUE,
	WIVW_ERROR_NULL_HANDLE,
	WIVW_ERROR_BUF_NOT_ENOUGH,
	WIVW_ERROR_RES_MISMATCH,	
	WIVW_ERROR_TRY_READ_LOCK_FAIL,
	WIVW_ERROR_TRY_WRITE_LOCK_FAIL,
	WIVW_ERROR_RES_EXTRACT_FAIL,
	WIVW_ERROR_RES_UPDATE_NOT_SUPPORT,
    WIVW_ERROR_WRITE_WAV_LEN_ERROR,
};
#endif	//__WIVW_ERROR_H__
